language: python
python:
  - "3.6" # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install codecov pytest-cov
# command to run tests
script:
  - pytest tests/test_runner.py --cov-config=.coveragerc --cov=pyscenes
after_success:
  - codecov
